pkginstall: this statement may fall through
main.c:897:3: error: this statement may fall through [-Werror=implicit-fallthrough=]
   usage();
   ^~~~~~~
main.c:899:2: note: here
  case 1: /* missing package instance */
  ^~~~
main.c:901:3: error: this statement may fall through [-Werror=implicit-fallthrough=]
   usage();
   ^~~~~~~
main.c:903:2: note: here
  case 2: /* just right! */
  ^~~~
cc1: all warnings being treated as errors